[%
    T = {
        configure_1                                = "IntranetUserJS: Item history report link",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Item history report link &rsaquo; Configuration",
        configure_5                                = "Report ID:",
        configure_6                                = "Report ID:",
        configure_7                                = "Report ID:",
        configure_8                                = "Upgrade status",
        configure_9                                = "Upgrade status",
        configure_10                               = "Upgrade status",
        configure_11                               = "Plugin has never been upgraded.",
        configure_12                               = "Plugin has never been upgraded.",
        configure_13                               = "Plugin has never been upgraded.",
        viewjs_1                                   = "IntranetUserJS: Item history report link",
        viewjs_2                                   = "&rsaquo; ItemHistoryReportLink &rsaquo; View JS plugin",
    }
%]