[%
    T = {
        configure_1                                = "IntranetUserJS: Niteen havaintohistorian raporttilinkki",
        configure_2                                = "Etusivu",
        configure_3                                = "Liitännäiset",
        configure_4                                = "&rsaquo; IntranetUserJS: Niteen havaintohistorian raporttilinkki &rsaquo; Asetukset",
        configure_5                                = "Raportin ID:",
        configure_6                                = "Raportin ID:",
        configure_7                                = "Raportin ID:",
        configure_8                                = "Päivityksen tila",
        configure_9                                = "Päivityksen tila",
        configure_10                               = "Päivityksen tila",
        configure_11                               = "Liitännäistä ei ole koskaan päivitetty.",
        configure_12                               = "Liitännäistä ei ole koskaan päivitetty.",
        configure_13                               = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "IntranetUserJS: Niteen havaintohistorian raporttilinkki",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Niteen havaintohistorian raporttilinkki &rsaquo; Näytä JS-liitännäinen",
    }
%]