[%
    T = {
        configure_1                                = "IntranetUserJS: Item history report link Configuration",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Item history report link &rsaquo; Configuration",
        configure_5                                = "Rapport-ID som används för att visa objektets historik:",
        configure_6                                = "Report ID used to display item history:",
        configure_7                                = "Niteen havaintohistorian näyttämiseen käytettävän raportin ID:",
        configure_8                                = "Uppgraderingsstatus",
        configure_9                                = "Upgrade status",
        configure_10                               = "Päivityksen tila",
        configure_11                               = "Pluginet har aldrig uppgraderats.",
        configure_12                               = "Plugin has never been upgraded.",
        configure_13                               = "Liitännäistä ei ole koskaan päivitetty.",
        viewjs_1                                   = "IntranetUserJS: Item history report link",
        viewjs_2                                   = "&rsaquo; ItemHistoryReportLink &rsaquo; View JS Tool",
    }
%]
