[%
    T = {
        configure_1                                = "IntranetUserJS: Länk till rapport över exemplarhistorik",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Länk till rapport över exemplarhistorik &rsaquo; Inställningar",
        configure_5                                = "Rapport-ID:",
        configure_8                                = "Uppdateringsstatus",
        configure_11                               = "Pluginet har aldrig uppdaterats.",
        viewjs_1                                   = "IntranetUserJS: Länk till rapport över exemplarhistorik",
        viewjs_2                                   = "&rsaquo; IntranetUserJS: Länk till rapport över exemplarhistorik &rsaquo; Visa JS-plugin",
    }
%]