[%
    T = {
        configure_1                                = "IntranetUserJS: Länk till rapport över exemplarhistorik Konfiguration",
        configure_2                                = "Hem",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; IntranetUserJS: Länk till rapport över exemplarhistorik &rsaquo; Konfiguration",
        configure_5                                = "Rapport-ID som används för att visa objektets historik:",
        configure_6                                = "Rapport-ID som används för att visa objektets historik:",
        configure_7                                = "Rapport-ID som används för att visa objektets historik:",
        configure_8                                = "Uppgraderingsstatus",
        configure_9                                = "Uppgraderingsstatus",
        configure_10                               = "Uppgraderingsstatus",
        configure_11                               = "Pluginet har aldrig uppgraderats.",
        configure_12                               = "Pluginet har aldrig uppgraderats.",
        configure_13                               = "Pluginet har aldrig uppgraderats.",
        viewjs_1                                   = "IntranetUserJS: Länk till rapport över exemplarhistorik",
        viewjs_2                                   = "&rsaquo; ItemHistoryReportLink &rsaquo; Visa JS-verktyg",
    }
%]